apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: ms-pedido-api
spec:
  image: wolwer/ms-pedido-api
  interval: 1m

---

apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: ms-pedido-api-policy
spec:
  imageRepositoryRef:
    name: ms-pedido-api
  policy:
    semver:
      range: ">=x1.0.0"

---

apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageUpdateAutomation
metadata:
  name: ms-pedido-api-update
spec:
  git:
    checkout:
      ref:
        branch: main
    commit:
      author:
        email: ricardo@dtmm.com.br
        name: FluxCD
      messageTemplate: "Update image to {{ .ImageName }}:{{ .NewTag }}"
    push:
      branch: main
  interval: 1m
  sourceRef:
    kind: GitRepository
    name: ms-pedido-api
  update:
    strategy: Setters

---

apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: ms-pedido-api
spec:
  interval: 1m
  url: https://github.com/FIAP-Tech-Chalenge/ms-pedido-api.git
  ref:
    branch: main
