apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: ms-admin-api
spec:
  image: wolwer/ms-admin-api
  interval: 1m

---

apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: ms-admin-api
spec:
  imageRepositoryRef:
    name: ms-admin-api
  policy:
    semver:
      range: ">=1.0.0"

---

apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: ms-admin-api
  namespace: default
spec:
  interval: 1m
  url: https://github.com/FIAP-Tech-Chalenge/ms-admin-api.git
  ref:
    branch: main

---

apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: ms-admin-api
  namespace: default
spec:
  interval: 1m
  path: ./k8s/FluxCD
  prune: true
  sourceRef:
    kind: GitRepository
    name: ms-admin-api
  images:
    - name: wolwer/ms-admin-api
      newTag: "{{ .ImagePolicy.latestImage }}"
  targetNamespace: default