apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-admin-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: hostpath
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-admin-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: hostpath
  hostPath:
    path: "/mnt/data/postgres-admin"