apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-admin-api
  labels:
    app: ms-admin-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ms-admin-api
  template:
    metadata:
      labels:
        app: ms-admin-api
    spec:
      containers:
        - name: ms-admin-api
          image: wolwer/ms-admin-api:v1.0.0
          imagePullPolicy: Always
          ports:
            - containerPort: 8081
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres-admin:5433/admin
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: my-secret
                  key: ADMIN_DATA_USER
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: my-secret
                  key: ADMIN_DATA_PASSWORD
            - name: SPRING_PROFILES_ACTIVE
              valueFrom:
                configMapKeyRef:
                  name: my-configmap
                  key: SPRING_PROFILES_ACTIVE
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: "kafka:9092"
          resources:
            requests:
              cpu: "100m"
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8081
            initialDelaySeconds: 180
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8081
            initialDelaySeconds: 180
            periodSeconds: 30