apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-cliente-api
  labels:
    app: ms-cliente-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ms-cliente-api
  template:
    metadata:
      labels:
        app: ms-cliente-api
    spec:
      containers:
        - name: ms-cliente-api
          image: wolwer/ms-cliente-api:v1.0.1
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres-cliente:5432/cliente
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: my-secret
                  key: CLIENTE_DATA_USER
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: my-secret
                  key: CLIENTE_DATA_PASSWORD
            - name: SPRING_PROFILES_ACTIVE
              valueFrom:
                configMapKeyRef:
                  name: my-configmap
                  key: SPRING_PROFILES_ACTIVE
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: "kafka:9092"
          resources:
            requests:
              cpu: "100m"
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 180
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 180
            periodSeconds: 30