apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.admin.name }}-service
  labels:
    app: {{ .Values.admin.name }}
spec:
  type: NodePort
  selector:
    app: {{ .Values.admin.name }}
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
      nodePort: 30002
