apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.admin.name }}
  labels:
    app: {{ .Values.admin.name }}
spec:
  replicas: {{ .Values.admin.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.admin.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.admin.name }}
    spec:
      containers:
        - name: {{ .Values.admin.name }}
          image: "{{ .Values.admin.image.repository }}:{{ .Values.admin.image.tag }}"
          ports:
            - containerPort: {{ .Values.admin.service.port }}
          env:
            - name: SPRING_DATASOURCE_URL
              value: {{ .Values.admin.datasource.url }}
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: my-secret
                  key: ADMIN_DATA_USER
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: my-secret
                  key: ADMIN_DATA_PASSWORD
            - name: SPRING_PROFILES_ACTIVE
              value: {{ .Values.admin.springProfilesActive }}
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: {{ .Values.admin.kafkaBootstrapServers }}
          resources:
            requests:
              cpu: "{{ .Values.admin.resources.requests.cpu }}"
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: {{ .Values.admin.service.port }}
            initialDelaySeconds: 180
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: {{ .Values.admin.service.port }}
            initialDelaySeconds: 180
            periodSeconds: 30