apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.cliente.name }}
spec:
  replicas: {{ .Values.cliente.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.cliente.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.cliente.name }}
    spec:
      containers:
        - name: {{ .Values.cliente.name }}
          image: "{{ .Values.cliente.image.repository }}:{{ .Values.cliente.image.tag }}"
          ports:
            - containerPort: {{ .Values.cliente.service.port }}
          env:
            - name: SPRING_DATASOURCE_URL
              value: {{ .Values.cliente.datasource.url }}
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.cliente.datasource.username.secretKeyRef.name }}
                  key: {{ .Values.cliente.datasource.username.secretKeyRef.key }}
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.cliente.datasource.password.secretKeyRef.name }}
                  key: {{ .Values.cliente.datasource.password.secretKeyRef.key }}
            - name: SPRING_PROFILES_ACTIVE
              value: {{ .Values.cliente.springProfilesActive }}
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: {{ .Values.cliente.kafkaBootstrapServers }}
          resources:
            requests:
              cpu: "{{ .Values.cliente.resources.requests.cpu }}"
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: {{ .Values.cliente.service.port }}
            initialDelaySeconds: 180
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: {{ .Values.cliente.service.port }}
            initialDelaySeconds: 180
            periodSeconds: 30