apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.cliente.name }}-service
  labels:
    app: {{ .Values.cliente.name }}
spec:
  type: NodePort
  selector:
    app: {{ .Values.cliente.name }}
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30001
