apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Values.pedido.hpa.name }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Values.pedido.name }}
  minReplicas: {{ .Values.pedido.hpa.minReplicas }}
  maxReplicas: {{ .Values.pedido.hpa.maxReplicas }}
  targetCPUUtilizationPercentage: {{ .Values.pedido.hpa.targetCPUUtilizationPercentage }}