apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.pedido.name }}
  labels:
    app: {{ .Values.pedido.name }}
spec:
  replicas: {{ .Values.pedido.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.pedido.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.pedido.name }}
    spec:
      containers:
        - name: {{ .Values.pedido.name }}
          image: "{{ .Values.pedido.image.repository }}:{{ .Values.pedido.image.tag }}"
          ports:
            - containerPort: {{ .Values.pedido.service.port }}
          env:
            - name: SPRING_DATASOURCE_URL
              value: {{ .Values.pedido.datasource.url }}
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.pedido.datasource.username.secretKeyRef.name }}
                  key: {{ .Values.pedido.datasource.username.secretKeyRef.key }}
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.pedido.datasource.password.secretKeyRef.name }}
                  key: {{ .Values.pedido.datasource.password.secretKeyRef.key }}
            - name: SPRING_PROFILES_ACTIVE
              value: {{ .Values.pedido.springProfilesActive }}
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: {{ .Values.pedido.kafkaBootstrapServers }}
          resources:
            requests:
              cpu: "{{ .Values.pedido.resources.requests.cpu }}"
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: {{ .Values.pedido.service.port }}
            initialDelaySeconds: 180
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: {{ .Values.pedido.service.port }}
            initialDelaySeconds: 180
            periodSeconds: 30