apiVersion: v1
kind: Secret
metadata:
  name: my-secret
  labels:
    app: app-tech
type: Opaque
data:
  DATA_USERNAME: cG9zdGdyZXM=  # "postgres" em base64
  DATA_PASSWORD: c1o2cVJ2YTJRTVJHenlBc24zQXI=  # "my-secret-pw" em base64