---
# k8s/tech-chart/templates/mongo-pv.yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-pedido-pv
spec:
  capacity:
    storage: {{ .Values.mongodb.pvc.storage }}
  accessModes:
    - ReadWriteOnce
  storageClassName: hostpath
  hostPath:
    path: "/mnt/data/mongo"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.mongodb.pvc.name }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.mongodb.pvc.storage }}
  storageClassName: hostpath