apiVersion: v1
kind: Service
metadata:
  name: postgres-cliente
spec:
  selector:
    app: postgres-cliente
  ports:
    - protocol: TCP
      port: {{ .Values.postgresCliente.service.port }}
      targetPort: {{ .Values.postgresCliente.service.port }}