# k8s/tech-chart/templates/postgres-admin-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-admin
spec:
  replicas: {{ .Values.postgresAdmin.replicaCount }}
  selector:
    matchLabels:
      app: postgres-admin
  template:
    metadata:
      labels:
        app: postgres-admin
    spec:
      containers:
        - name: postgres-admin
          image: {{ .Values.postgresAdmin.image.repository }}
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: my-secret
                  key: ADMIN_DATA_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: my-secret
                  key: ADMIN_DATA_PASSWORD
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.postgresAdmin.configmap.POSTGRES_DB_CONFIGMAP }}
                  key: ADMIN_DATA_DATABASE
          ports:
            - containerPort: {{ .Values.postgresAdmin.service.port }}
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgres-admin-storage
      volumes:
        - name: postgres-admin-storage
          persistentVolumeClaim:
            claimName: postgres-admin-pvc
