apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.postgresAdmin.name }}
spec:
  replicas: {{ .Values.postgresAdmin.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.postgresAdmin.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.postgresAdmin.name }}
    spec:
      containers:
        - name: {{ .Values.postgresAdmin.name }}
          image: "{{ .Values.postgresAdmin.image.repository }}:{{ .Values.postgresAdmin.image.tag }}"
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: my-secret
                  key: ADMIN_DATA_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: my-secret
                  key: ADMIN_DATA_PASSWORD
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: my-configmap
                  key: ADMIN_DATA_DATABASE
          ports:
            - containerPort: {{ .Values.postgresAdmin.service.port }}
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgres-admin-storage
      volumes:
        - name: postgres-admin-storage
          persistentVolumeClaim:
            claimName: {{ .Values.postgresAdmin.pvc.name }}