apiVersion: v1
kind: Service
metadata:
  name: postgres-admin
spec:
  selector:
    app: postgres-admin
  ports:
    - protocol: TCP
      port: {{ .Values.postgresAdmin.service.port }}
      targetPort: {{ .Values.postgresAdmin.service.port }}
