apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.postgresCliente.name }}
spec:
  selector:
    app: {{ .Values.postgresCliente.name }}
  ports:
    - protocol: TCP
      port: {{ .Values.postgresCliente.service.port }}
      targetPort: {{ .Values.postgresCliente.service.port }}