apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: ms-pedido-api-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ms-pedido-api
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80