cliente:
  name: ms-cliente-api
  replicaCount: 3
  image:
    repository: wolwer/ms-cliente-api
    tag: latest
  hpa:
    name: ms-cliente-api-hpa
    minReplicas: 1
    maxReplicas: 5
    targetCPUUtilizationPercentage: 80
  service:
    type: NodePort
    port: 8080
    targetPort: 8080
    nodePort: 30001
  deployment:
    replicas: 3
    image: wolwer/ms-cliente-api
  datasource:
    url: jdbc:postgresql://postgres-cliente:5432/cliente
    username:
      secretKeyRef:
        name: my-secret
        key: CLIENTE_DATA_USER
    password:
      secretKeyRef:
        name: my-secret
        key: CLIENTE_DATA_PASSWORD
  springProfilesActive: hom
  kafkaBootstrapServers: kafka:9092
  resources:
      requests:
        cpu: "100m"
  ingress:
    name: ms-cliente-api-ingress
    enabled: true
    annotations: {}
    hosts:
    - host: cliente
      paths:
        - path: /
          pathType: ImplementationSpecific
    tls: []

postgresCliente:
  name: postgres-cliente
  replicaCount: 1
  image:
    repository: postgres
    tag: latest
  env:
    user:
      secretKeyRef:
        name: my-secret
        key: CLIENTE_DATA_USER
    password:
      secretKeyRef:
        name: my-secret
        key: CLIENTE_DATA_PASSWORD
    db:
      configMapKeyRef:
        name: my-configmap
        key: CLIENTE_DATA_DATABASE
  service:
    port: 5432
  pvc:
    name: postgres-cliente-pvc
    storage: 1Gi

admin:
  name: ms-admin-api
  replicaCount: 3
  image:
    repository: wolwer/ms-admin-api
    tag: latest
  hpa:
    name: ms-admin-api-hpa
    minReplicas: 1
    maxReplicas: 5
    targetCPUUtilizationPercentage: 80
  service:
    type: NodePort
    port: 8081
    targetPort: 8081
    nodePort: 30002
  deployment:
    replicas: 3
    image: wolwer/ms-admin-api
  datasource:
    url: jdbc:postgresql://postgres-admin:5433/admin
    username:
      secretKeyRef:
        name: my-secret
        key: ADMIN_DATA_USER
    password:
      secretKeyRef:
        name: my-secret
        key: ADMIN_DATA_PASSWORD
  springProfilesActive: hom
  kafkaBootstrapServers: kafka:9092
  resources:
    requests:
      cpu: "100m"
  ingress:
    name: ms-admin-api-ingress
    enabled: true
    annotations: {}
    hosts:
      - host: admin
        paths:
          - path: /
            pathType: ImplementationSpecific
    tls: []

postgresAdmin:
  name: postgres-admin
  replicaCount: 1
  image:
    repository: postgres
    tag: latest
  env:
    user:
      secretKeyRef:
        name: my-secret
        key: ADMIN_DATA_USER
    password:
      secretKeyRef:
        name: my-secret
        key: ADMIN_DATA_PASSWORD
    db:
      configMapKeyRef:
        name: my-configmap
        key: ADMIN_DATA_DATABASE
  service:
    port: 5433
  pvc:
    name: postgres-admin-pvc
    storage: 1Gi

pedido:
  name: ms-pedido-api
  replicaCount: 3
  image:
    repository: wolwer/ms-pedido-api
    tag: latest
  hpa:
    name: ms-pedido-api-hpa
    minReplicas: 1
    maxReplicas: 5
    targetCPUUtilizationPercentage: 80
  service:
    type: NodePort
    port: 8082
    targetPort: 8082
    nodePort: 30003
  deployment:
    replicas: 3
    image: wolwer/ms-pedido-api
  datasource:
    url: mongodb://mongo-pedido:27017/pedido
    username:
      secretKeyRef:
        name: my-secret
        key: PEDIDO_DATA_USER
    password:
      secretKeyRef:
        name: my-secret
        key: PEDIDO_DATA_PASSWORD
  springProfilesActive: hom
  kafkaBootstrapServers: kafka:9092
  resources:
    requests:
      cpu: "100m"
  ingress:
    name: ms-pedido-api-ingress
    enabled: true
    annotations: {}
    hosts:
      - host: pedido
        paths:
          - path: /
            pathType: ImplementationSpecific
    tls: []


mongodb:
  name: mongo-pedido
  replicaCount: 1
  image:
    repository: mongo:latest
  service:
    port: 27017
  pvc:
    name: mongo-pedido-pvc
    storage: 1Gi

zookeeper:
  replicaCount: 1
  image:
    repository: confluentinc/cp-zookeeper:latest
  pvc:
    storage: 2Gi
  externalService:
    enabled: true

kafka:
  replicaCount: 1
  image:
    repository: confluentinc/cp-kafka:latest
  pvc:
    storage: 10Gi
  externalService:
    enabled: true
